<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Todo App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@200;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
<div id="container">
<h1>TODO List</h1>
<form action="/tasks" method="POST">
    <label for="message">Add task:</label>
    <input id="message" type="text" name="message">
    <input type="submit" value="Add">
</form>
<div id="task-list">
    <?= \App\ViewHelpers\TaskHelper::renderTasks($tasks);?>
</div>
<div id="completed-link">
    <a href="completed">Show completed tasks</a>
</div>
</div>
</body>
</html>
